# Generated by Django 2.0.1 on 2018-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaseries',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
