# Generated by Django 2.0.1 on 2018-02-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0002_categoriaseries_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriahilo',
            fields=[
                ('codigo', models.IntegerField(help_text='debe ser numérico entero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='máximo 30 caracteres, no puede haber 2 nombres iguales', max_length=30, unique=True)),
                ('codigohilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbody.Hilos')),
            ],
        ),
    ]
