# Generated by Django 2.0.1 on 2018-02-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0003_categoriahilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriahilo',
            name='codigohilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webbody.Hilos'),
        ),
    ]
