# Generated by Django 2.0.1 on 2018-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0005_auto_20180203_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriahilo',
            name='imagen',
            field=models.ImageField(default='images/failed.jpg', upload_to='webbody/static/images'),
        ),
    ]
