# Generated by Django 2.0.1 on 2018-02-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0007_auto_20180203_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriahilo',
            name='imagen',
            field=models.ImageField(default='webbody/static/images/failed.jpg', upload_to='images/'),
        ),
    ]
