# Generated by Django 2.0.1 on 2018-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0008_auto_20180203_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriahilo',
            name='tipo',
            field=models.CharField(choices=[('foro', 'Foro'), ('descargas', 'Descargas')], default='foro', max_length=9),
        ),
    ]
