# Generated by Django 2.0.1 on 2018-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0010_auto_20180204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriahilo',
            name='imagen',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='portada',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='portada',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='portada',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='portada',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='portada',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imgprincipal',
            field=models.ImageField(default='images/failed.jpg', upload_to='images/'),
        ),
    ]
