# Generated by Django 2.0.1 on 2018-02-04 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webbody', '0012_remove_categoriaseries_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgprincipal', models.ImageField(default='images/failed.jpg', upload_to='images/')),
                ('fnacimiento', models.CharField(help_text='formato:00/00/0000', max_length=10, null=True)),
                ('nacionalidad', models.CharField(help_text='máximo 30 caracteres', max_length=30, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nombreusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbody.Perfil'),
        ),
        migrations.AlterField(
            model_name='hilos',
            name='comentario',
            field=models.ManyToManyField(through='webbody.Comentarios', to='webbody.Perfil'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
