# Generated by Django 2.0.1 on 2018-02-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0014_auto_20180205_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='nombreusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webbody.Perfil'),
        ),
    ]
