# Generated by Django 2.0.1 on 2018-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0016_auto_20180206_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilos',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
