# Generated by Django 2.0.1 on 2018-02-07 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0017_auto_20180206_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='fechahora',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hilos',
            name='codusuhilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webbody.Perfil'),
        ),
        migrations.AddField(
            model_name='hilos',
            name='contenido',
            field=models.CharField(default='', help_text='Texto libre', max_length=9999),
        ),
        migrations.AddField(
            model_name='hilos',
            name='fechahora',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nombreusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbody.Perfil'),
        ),
        migrations.AlterField(
            model_name='hilos',
            name='categoriahilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbody.Categoriahilo'),
        ),
        migrations.AlterUniqueTogether(
            name='comentarios',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hilos',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='hilos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='hilos',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='hilos',
            name='usuario',
        ),
    ]
