# Generated by Django 2.0.1 on 2018-02-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0018_auto_20180207_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilos',
            name='codusuhilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
