# Generated by Django 2.0.1 on 2018-02-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0019_auto_20180207_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilos',
            name='codusuhilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webbody.Perfil'),
        ),
    ]
