# Generated by Django 2.0.1 on 2018-02-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0020_auto_20180207_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='hora',
        ),
    ]
