# Generated by Django 2.0.1 on 2018-02-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0021_remove_comentarios_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='texto',
            field=models.CharField(help_text='Texto libre', max_length=9999),
        ),
    ]
