# Generated by Django 2.0.1 on 2018-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0022_auto_20180210_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='size',
            field=models.CharField(help_text='maximo 10 caracteres', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imgprincipal',
            field=models.ImageField(default='images/anonimo.png', upload_to='images/'),
        ),
    ]
