# Generated by Django 2.0.1 on 2018-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0023_auto_20180218_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilos',
            name='titulo',
            field=models.CharField(help_text='máximo 200 caracteres', max_length=200, unique=True),
        ),
    ]
