# Generated by Django 2.0.1 on 2018-02-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0024_auto_20180218_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlace',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
