# Generated by Django 2.0.1 on 2018-02-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0025_auto_20180219_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriahilo',
            name='imagen',
            field=models.ImageField(default='images/cancel.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='portada',
            field=models.ImageField(default='images/cancel.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='portada',
            field=models.ImageField(default='images/cancel.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='portada',
            field=models.ImageField(default='images/cancel.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='portada',
            field=models.ImageField(default='images/cancel.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='portada',
            field=models.ImageField(default='images/cancel.png', upload_to='images/'),
        ),
    ]
