# Generated by Django 2.0.1 on 2018-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0027_auto_20180219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='numjugadores',
            field=models.IntegerField(),
        ),
    ]
