# Generated by Django 2.0.1 on 2018-02-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0028_auto_20180219_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='series',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='series',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='series',
            name='titulohilo',
        ),
        migrations.DeleteModel(
            name='Categoriaseries',
        ),
        migrations.DeleteModel(
            name='Programas',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
