# Generated by Django 2.0.1 on 2018-02-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbody', '0029_auto_20180219_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='musica',
            name='size',
            field=models.CharField(help_text='maximo 10 caracteres', max_length=10),
        ),
    ]
